### ISSUE TITLE
new serving container image would be needed with trust_remote_code=True

### ISSUE THREAD

**Issue by dhshah13** [rh-aiservices-bu/llm-on-openshift#74]
Getting this error 

Traceback (most recent call last):
  File "/opt/app-root/src/app.py", line 35, in <module>
    model = SentenceTransformer(args.model_path)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/app-root/lib64/python3.12/site-packages/sentence_transformers/SentenceTransformer.py", line 287, in __init__
    modules = self._load_sbert_model(
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/app-root/lib64/python3.12/site-packages/sentence_transformers/SentenceTransformer.py", line 1487, in _load_sbert_model
    module = Transformer(model_name_or_path, cache_dir=cache_folder, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/app-root/lib64/python3.12/site-packages/sentence_transformers/models/Transformer.py", line 53, in __init__
    config = AutoConfig.from_pretrained(model_name_or_path, **config_args, cache_dir=cache_dir)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/app-root/lib64/python3.12/site-packages/transformers/models/auto/configuration_auto.py", line 937, in from_pretrained
    trust_remote_code = resolve_trust_remote_code(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/app-root/lib64/python3.12/site-packages/transformers/dynamic_module_utils.py", line 639, in resolve_trust_remote_code
    raise ValueError(
ValueError: Loading /mnt/models requires you to execute the configuration file in that repo on your local machine. Make sure you have read the code there to avoid malicious use, then set the option `trust_remote_code=True` to remove this error.

AS per slack conversation 

https://github.com/rh-aiservices-bu/llm-on-openshift/blob/1b864db3eb23a4fdaa7f2c57ab58ad2a25711a94/llm-servers/sbert/gpu/app.py#L35
So model = SentenceTransformer(args.model_path, trust_remote_code=True)

https://redhat-internal.slack.com/archives/C03UGJY6Z1A/p1721669067245059?thread_ts=1721160037.008339&cid=C03UGJY6Z1A

**Comment by dhshah13** [comment]
updated the code with the changes.
